first_app/urls.py
from django.conf.urls import url
from first_app import views

#template tagging
app_name = 'first_app'

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^relative/$', views.related, name='relative'),
    url(r'^other/$', views.other, name='other'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/', views.user_login, name='user_login'),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='user.index'), # fisrt url using import
    path('first-app/', include('first_app.urls')), #second url using string
    path('formpage/', views.form_name_views, name="form_name"),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.DO_NOTHING)
    date = models.DateField(default=None)

    def __str__(self):
        return str(self.date)

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #addition
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to start with z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter email again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        verify_email = all_clean_data['verify_email']

        if email != verify_email:
            raise forms.ValidationError("they dont match")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_app/views.py
from django.shortcuts import render
from . import forms
from first_app.models import Topic, Webpage, AccessRecord
from first_app.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    my_dict = {'access_record': webpage_list,
               'text': 'hello world',
               'number': 100}
    return render(request, 'first_app/index.html', context=my_dict)

def form_name_views(request):
    form = forms.FormName()

    if request.method == "POST":
        form = forms.FormName(request.POST)
        if form.is_valid():
            print("validation success")
            print("Name:"+form.cleaned_data['name'])
            print("Email:"+form.cleaned_data['email'])
            print("Text:"+form.cleaned_data['text'])
    return render(request, 'first_app/form.html', {'form': form})

def other(request):
    return render(request, 'first_app/other.html')

def related(request):
    return render(request, 'first_app/relative.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pics' in request.FILES:
                profile.profile_pic = request.FILES['profile_pics']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'first_app/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('first_app:index'))

            else:
                return HttpResponseRedirect("ACCOUNT NOT ACTIVE")
        else:
            print("account break")
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("invalid login detail")
    else:
        return render(request, 'first_app/login.html')

def special(request):
    return HttpResponse("Logged success")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_app:index'))

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar-brand"><a href="{% url 'first_app:index' %}">BRAND</a></li>
                <li class="navbar-link"><a href="{% url 'admin:index' %}">ADMIN</a></li>
                <li class="navbar-link"><a href="{% url 'first_app:other' %}">Other</a></li>
                <li class="navbar-link"><a href="{% url 'first_app:register' %}">Register</a></li>
                {% if user.is_authenticated %}
                <li class="navbar-link"><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="navbar-link"><a href="{% url 'first_app:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!--inheritance here-->
        {% endblock %}
    </div>
</body>
</html>

templates/first_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <form action="#" method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load staticfiles %}
{% load my_extras %}
  {% block title %}
        <title>Index</title>
  {% endblock %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Hello this is index.html</h1>
      <h2>Goto /formpage to fill out the form</h2>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <img src="{% static 'images/shin.png' %}" alt="kingdom.png">
          <div class="container">
            {% if access_record %}
              <table>
                <thead>
                  <th>Name</th>
                  <th>Date</th>
                </thead>
                {% for acc in access_record%}
              <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
              </tr>
              {% endfor %}
            </table>
            {% else %}
              <p>no record</p>
            {% endif %}
          </div>
      </div>
          <div class="col-sm-6">
            {{ text|cut:'world' }}
            {{ number|add:"97" }}
          </div>
      </div>
    </div>
{% endblock %}

templates/first_app/login.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block title %}
    <title>Login</title>
{% endblock %}
{% block body_block %}
<form action="{% url 'first_app:user_login' %} %" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username">
    <label for="password">Password</label>
    <input type="password" name="password">
    {% csrf_token %}
    <input type="submit" value="ok" class="btn btn-default">
</form>
{% endblock %}

templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block title %}
        <title>Other</title>
    {% endblock %}
    {% block body_block %}
        <p>this is other page</p>
        <a href="{% url 'first_app:index' %}">index</a>
    {% endblock %}

templates/first_app/register.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% load staticfiles %}
{% block title %}
    <title>Register</title>
{% endblock %}
{% block body_block %}
    {% if registered %}
        <h2>Thanks for your registration</h2>
    {% else %}
        <h2>Register here!!!</h2>
        <p>Fill out the form: </p>
        <form enctype="multipart/form-data" method="POST">
            {{user_form.as_p}}
            {{profile_form.as_p}}
            {% csrf_token %}
            <input type="submit" value="ok" class="btn btn-primary">
        </form>
    {% endif %}
{% endblock %}

templates/first_app/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Relate page</title>
</head>
<body>

</body>
</html>